version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_ci:/var/lib/mysql
    command: >
      mysqld
      --innodb-lock-wait-timeout=300
      --max_connections=300
      --innodb-thread-concurrency=8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1G

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rspec"
    environment:
      RAILS_ENV: test
      DATABASE_URL: mysql2://root:password@db:3306/runteq_graduation_test
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    depends_on:
      db:
        condition: service_healthy
      chrome:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "1.5"

  chrome:
    image: seleniarm/standalone-chromium:121.0
    ports:
      - "4444:4444"
    environment:
      SE_OPTS: "--session-timeout 600 --max-sessions 2"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"

  redis:
    deploy:
      replicas: 0

volumes:
  mysql_data_ci: