services:
  db:
    image: mysql:latest
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
      
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p ${PORT:-3000}"
    tty: true
    stdin_open: true
    volumes:
      - .:/runteq_graduation_productio-
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/runteq_graduation_productio-/node_modules
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:121.0
    ports:
      - "4444:4444"

volumes:
  mysql_data:
  bundle_data:
  node_modules: