name: Rails CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure database.yml
        run: cp config/database.yml.ci config/database.yml

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build

      - name: Prepare Database
        run: |
          docker-compose exec web bash -c "bundle exec rails db:create db:schema:load"

      - name: Run RSpec
        run: |
          docker-compose exec web bash -c "RAILS_ENV=test bundle exec rspec"

      - name: Run Rubocop
        run: |
          docker-compose exec web bash -c "bundle exec rubocop"

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml down