name: Rails CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Configure database.yml
        if: env.CI
        run: cp config/database.yml.ci config/database.yml

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build
      
      - name: Check Docker Compose Services
        run: docker-compose ps

      - name: Check MySQL Logs
        run: docker-compose logs db

      - name: Prepare Database
        run: |
          docker-compose exec web bash -c "bundle exec rails db:create db:schema:load"

      - name: Run RSpec
        run: |
          docker-compose exec web bash -c "RAILS_ENV=test bundle exec rspec"

      - name: Run Rubocop
        run: |
          docker-compose exec web bash -c "bundle exec rubocop"

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml down