name: Rails CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Configure database.yml
        run: cp config/database.yml.ci config/database.yml

      - name: Increase Swap
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            docker-compose exec db mysqladmin ping -h db --silent && break
            echo "Waiting for MySQL to be ready..."
            sleep 1
          done

      - name: Check Web Logs
        run: docker-compose logs web

      - name: Restart Web Service
        run: docker-compose restart web

      - name: Prepare Database
        run: |
          docker-compose exec web bash -c "bundle exec rails db:create db:schema:load"

      - name: Run RSpec
        run: |
          docker-compose exec web bash -c "RAILS_ENV=test bundle exec rspec"

      - name: Run Rubocop
        run: |
          docker-compose exec web bash -c "bundle exec rubocop"

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml down